---
title: "COVID_19_Viz"
author: "Ijeamaka Anyene"
date: "3/31/2020"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(waffle)
library(ggtext)
library(cowplot)
```
## Data Set Up

```{r}
natural_history_v1 = tibble(
  periods = rep(c("Incubation Period", "Clinical Disease", "Latent Period", "Infectious Period"), 
      times = 4),
  time = c(flu_time = c(2, 8, 1, 5),
           smallpox_time = c(7, 3, 9, 1),
           sars_time = c(4, 6, 4, 6),
           covid19_time = c(5, 5, 3, 7)),
  disease_name = rep(c("Influenza", "Smallpox", "SARS", "SARS-CoV-2"), each = 4),
  diseases_detailed = rep(c(paste0("**Influenza**<br>",
  "Individuals are typically <b style='color:#d0587e'>contagious</b> before they experience <b style='color:#72aaa1'>symptoms</b><br>"), 
             paste0("**Smallpox**<br>", 
                    "Individuals are <b style='color:#72aaa1'>symptomatic</b> before they are <b style='color:#d0587e'>contagious</b><br>"),
  paste0("**SARS**<br>", 
         "Individuals are <b style='color:#d0587e'>contagious</b> only when they experience <b style='color:#72aaa1'>symptoms</b>"),
  paste0("**SARS-CoV-2**<br>", 
             "Individuals are <b style='color:#d0587e'>contagious</b> before they experience <b style='color:#72aaa1'>symptoms</b><br>")), each = 4)
)

```

```{r}
my_palette = rcartocolor::carto_pal(n = 7, name = "TealRose")
cols = c(my_palette[c(3, 2, 4, 7)])
```

```{r}
labs =c("*Incubation Period*<br>Infected but not symptomatic", 
        "*Clinical Disease*<br>Typically symptomatic", 
        "*Latent Period*<br>Infected but not contagious", 
        "*Infectious Period*<br>Contagious")
```

```{r}
influenza_text = c(paste0("<span style='font-size:18pt'>**Influenza**<br></span>",
                          "<span style='font-size:14pt'>Individuals are typically <b style='color:#d0587e'>contagious </b>**before** they experience <b style='color:#72aaa1'>symptoms</b></span><br><br>",
                          "<span style='font-size:12pt'>
                          Individuals can infect others about a day before they develop symptoms.<br>
                          Consequently, control strategies that focus on vaccination, infection control,<br> 
                          and respiratory hygiene are the most effective.</span><br>"))

smallpox_text = c(paste0("<span style='font-size:18pt'>**Smallpox**</span><br>", 
                    "<span style='font-size:14pt'>Individuals are <b style='color:#72aaa1'>symptomatic </b>**before** they are <b style='color:#d0587e'>contagious</b></span><br><br>",
                    "<span style='font-size:12pt'>
                    Individuals did not typically infect others until after the development of<br> 
                    symptoms. This meant that case-based strategies that included<br> 
                    contact tracing and vaccination were very effective.</span><br>"))

sars_text = c(paste0("<span style='font-size:18pt'>**SARS**</span><br>",
                     "<span style='font-size:14pt'>Individuals are <b style='color:#72aaa1'>symptomatic </b>**before** they are <b style='color:#d0587e'>contagious</b></span><br><br>",
                     "<span style='font-size:12pt'>
                     Individuals typically cannot infect others until after they have symptoms.<br> 
                     This meant that case-based strategies such as case-finding and isolation, along with<br> 
                     contract tracing and quarantine, was enough to interrupt the 2003 SARS epidemic.</span><br>"))


sars_cov_2_text = c(paste0("<span style='font-size:18pt'>**SARS-CoV-2**</span><br>",
                           "<span style='font-size:14pt'>Some individuals are likely <b style='color:#d0587e'>contagious </b>**before** they experience <b style='color:#72aaa1'>symptoms</b></span><br><br>",
                           "<span style='font-size:12pt'>
                           Preliminary research reveals that some infected individuals are capable of<br> 
                           infecting others before they develop symptoms, while some individuals<br> 
                           never develop symptoms at all. Thus aggressive control strategies such as<br> 
                           social distancing, infection control, and personal protective equipment<br> 
                           are needed until a vaccine or therapeutic is available.</span><br>"))

```

```{r}
natural_history_v2 = tibble(
  periods = rep(c("Incubation Period", "Clinical Disease", "Latent Period", "Infectious Period"), 
      times = 4),
  time = c(flu_time = c(2, 8, 1, 5),
           smallpox_time = c(7, 3, 9, 1),
           sars_time = c(4, 6, 4, 6),
           covid19_time = c(5, 5, 3, 7)),
  disease_name = rep(c("Influenza", "Smallpox", "SARS", "SARS-CoV-2"), each = 4),
  diseases_detailed = rep(c(influenza_text,
                            smallpox_text,
                            sars_text,
                            sars_cov_2_text), each = 4)
)

```

## Version for Social Media

```{r}
natural_history_infographic = natural_history_v2 %>%
  mutate(periods_new = forcats::fct_relevel(periods, 
                                            c("Incubation Period", "Clinical Disease", 
                                                       "Latent Period", "Infectious Period")),
         diseases_detailed = forcats::fct_relevel(diseases_detailed, 
                                                  c(influenza_text,
                                                    smallpox_text,
                                                    sars_text,
                                                    sars_cov_2_text))) %>%
  ggplot(aes(fill = periods_new, 
             values = time)) +
  geom_waffle(n_rows = 10, 
              flip = TRUE, 
              color = "white", 
              size = 1) +
  facet_wrap(~diseases_detailed, 
             nrow = 2, 
             strip.position = "top",
             scales = "free") +
  scale_x_continuous(breaks = seq(1:10), 
                     labels = paste0("Day ", seq(1:10))) +
  scale_fill_manual(values = cols,
                    labels = labs,
                    name = NULL) + 
  guides(fill = guide_legend(title.position = "top", 
                                title.hjust = 0.5, nrow = 1,
                                label.position = "bottom",
                                override.aes = list(size = 5))) +
  labs(title = "Natural History of a Pathogen Informs Mitigation and Control Strategies",
       caption = c("Graphic: Ijeamaka Anyene")) +
  theme(plot.title = element_text(size = 24, face = "bold", 
                                  hjust = 0.5),
        plot.caption = element_markdown(size = 10, color = "black"),
        strip.background = element_blank(),
        legend.text = element_markdown(size = 13, 
                                    color = "black"),
        legend.key.height = unit(0.9, "lines"), 
        legend.key.width = unit(10, "lines"), # originally 11.2
        legend.key = element_blank(),
        strip.text = element_markdown(#size = 16,
                                      color = "black"),
        panel.background = element_blank(),
        panel.spacing = unit(2, "lines"),
        axis.text.x = element_text(size = 13),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.x = element_line(size = 0.75, arrow = arrow()),
        legend.position = "bottom")

natural_history_infographic
```

```{r}
ggsave("natural_history_infographic_v2.png", natural_history_infographic, device = "png",
       width = 15, height = 7) # originally width = 15, height = 9

```

**Blurb**


## Version for Sandi's Presentation
```{r}
natural_history_panel = natural_history_v1 %>%
  mutate(periods_new = forcats::fct_relevel(periods, c("Incubation Period", "Clinical Disease", 
                                                       "Latent Period", "Infectious Period")),
         diseases_detailed = forcats::fct_relevel(diseases_detailed, c(
           paste0("**Influenza**<br>","Individuals are typically <b style='color:#d0587e'>contagious</b> before they experience <b style='color:#72aaa1'>symptoms</b><br>"), 
             paste0("**Smallpox**<br>", "Individuals are <b style='color:#72aaa1'>symptomatic</b> before they are <b style='color:#d0587e'>contagious</b><br>"),
           paste0("**SARS**<br>", "Individuals are <b style='color:#d0587e'>contagious</b> only when they experience <b style='color:#72aaa1'>symptoms</b>"),
           paste0("**SARS-CoV-2**<br>", "Individuals are <b style='color:#d0587e'>contagious</b> before they experience <b style='color:#72aaa1'>symptoms</b><br>")))) %>%
  ggplot(aes(fill = periods_new, 
             values = time)) +
  geom_waffle(n_rows = 10, 
              flip = TRUE, 
              color = "white", 
              size = 1) +
  facet_wrap(~diseases_detailed, 
             nrow = 4, 
             strip.position = "top") +
  scale_x_continuous(breaks = seq(1:10), 
                     labels = paste0("Day ", seq(1:10))) +
  scale_fill_manual(values = cols,
                    labels = labs,
                    name = NULL) + 
  guides(fill = guide_legend(title.position = "top", 
                                title.hjust = 0.5, nrow = 1,
                                label.position = "bottom",
                                override.aes = list(size = 5))) +
  labs(title = "Natural History Timelines and Implications for Control") +
        #caption = paste0("Visualization: Ijeamaka Anyene, MPH<br>",
                         #"Data Sources: Carrat, 2008. Lauer, 2020.<br> Wei, 2020. CDC.")) +
  theme(plot.title = element_text(size = 24, face = "bold", 
                                  hjust = 0.5),
        plot.caption = element_markdown(size = 10, color = "black"),
        strip.background = element_blank(),
        legend.text = element_markdown(size = 13, 
                                    color = "black"),
        legend.key.height = unit(0.9, "lines"), 
        legend.key.width = unit(10, "lines"), # originally 11.2
        legend.key = element_blank(),
        strip.text = element_markdown(size = 16,
                                      color = "black"),
        panel.background = element_blank(),
        panel.spacing = unit(2, "lines"),
        axis.text.x = element_text(size = 13),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.x = element_line(size = 0.75, arrow = arrow()),
        legend.position = "bottom")
```

```{r}
natural_history_panel

```

```{r}
ggsave("natural_history_panel_v5.png", natural_history_panel, device = "png",
       width = 9, height = 9) # originally width = 15, height = 9

```





